// resources.js

let RESOURCES = {

    slideShow: ['./img/slide/1.jpg', './img/slide/2.jpg', './img/slide/3.jpg'],

    product: [{
        id: '0000006',
        title: '宇治抹茶奶茶',
        price: '￥14',
        img: './img/product/宇治抹茶奶茶.jpg',
        category: '奶茶',
        text: '甘甜丝滑的奶茶搭配味道清新的宇治抹茶，健康美味，口感独特，仿佛让人品味到古日本的风情。',
    }, {
        id: '0000001',
        title: '美式咖啡',
        price: '￥15',
        img: './img/product/美式咖啡.jpg',
        category: '咖啡',
        text: '咖啡的一种，是最普通的咖啡。是使用滴滤式咖啡壶所制作出的黑咖啡。',
    }, {
        id: '0000002',
        title: '拿铁咖啡',
        price: '￥18',
        img: './img/product/拿铁咖啡.jpg',
        category: '咖啡',
        text: '拿铁咖啡是意大利浓缩咖啡与牛奶的经典混合，意大利人也很喜欢把拿铁作为早餐的饮料。',
    }, {
        id: '0000003',
        title: '卡布奇诺',
        price: '￥20',
        img: './img/product/卡布奇诺.jpg',
        category: '咖啡',
        text: '卡布奇诺Cappuccino是原产意大利的一种带泡沫的咖啡，与拿铁咖啡的区别在与多了奶泡。',
    }, {
        id: '0000004',
        title: '摩卡奇诺',
        price: '￥22',
        img: './img/product/摩卡奇诺.jpg',
        category: '咖啡',
        text: '非常的香浓可口，白咖啡的咖啡因含量很低，加入大量的牛奶，淡淡的口味，唇齿间以浓浓奶香，当奶茶一样喝又不刺激肠胃，也是早餐和下午茶的首选。',
    }, {
        id: '0000005',
        title: '抹茶星冰乐',
        price: '￥15',
        img: './img/product/抹茶星冰乐.jpg',
        category: '独家',
        text: '甄选优质食材，香醇浓厚，口感细腻，味道香甜，美味可口，一抹浓郁香滑，让您品尝到不一样的美味。',
    }, {
        id: '0000007',
        title: '巧克力奶醇',
        price: '￥18',
        img: './img/product/巧克力奶醇.jpg',
        category: '独家',
        text: '巧克力Q奶醇一杯！一杯杯的思念，一口口的浪漫，就如这杯巧克力奶醇，捧在手心，仿佛就要融化一样！',
    }, {
        id: '0000008',
        title: '红豆布丁奶茶',
        price: '￥12',
        img: './img/product/红豆布丁奶茶.jpg',
        category: '奶茶',
        text: '原味奶茶搭配滑溜溜的布丁与细腻红润的红豆，清心养神，健脾活血，味道甘甜且不必担心发胖。',
    }, {
        id: '0000009',
        title: '芒椰芦荟奶茶',
        price: '￥14',
        img: './img/product/芒椰芦荟奶茶.jpg',
        category: '奶茶',
        text: '椰奶与鲜奶的完美交融，再加入绿色健康的芦荟汁来进行调味，酸酸甜甜的芒果粒则为其增添了一抹亚热带的风情。',
    }, {
        id: '0000010',
        title: '盘栽奶茶',
        price: '￥17',
        img: './img/product/盘栽奶茶.jpg',
        category: '奶茶',
        text: '原味奶茶加入甜滑甜滑的鲜奶油与香脆的奥利奥饼干末，独特的造型，香甜的口味，为你带来不一样的美妙感受。',
    }, {
        id: '0000011',
        title: '岩盐芝士奶茶',
        price: '￥16',
        img: './img/product/岩盐芝士奶茶.jpg',
        category: '奶茶',
        text: '原味奶茶融入岩盐芝士那淡淡的咸味，使得奶茶的口感更加香甜丝滑，又甜而不腻。',
    }, {
        id: '0000012',
        title: '珍珠奶茶',
        price: '￥10',
        img: './img/product/珍珠奶茶.jpg',
        category: '奶茶',
        text: '香甜的奶茶，加入一粒粒圆润的黑珍珠，经典的搭配，经典的味道，欢迎各位来品尝。',
    }, ]
}